# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: WhosAtMyFeeder add-on
version: "1.1.3"
slug: whosatmyfeeder
description: This app acts as a sidecar to Frigate to identify the species of the birds that Frigate detects.
url: "https://github.com/bertybuttface/addons/tree/main/whosatmyfeeder"
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 7767
panel_icon: "mdi:bird"
panel_title: "Who's At My Feeder?"
init: false
map:
  - share:rw
options:
  frigate:
    frigate_url: "http://ccab4aaf-frigate:5000"
    mqtt_server: "core-mosquitto"
    mqtt_auth: true
    mqtt_username: whosatmyfeeder
    mqtt_password: use-a-secure-password-here
    main_topic: frigate
    camera:
      - your
      - cameras
      - here
    object: bird
  classification:
    model: /usr/app/model.tflite
    name_database: /usr/app/birdnames.db
    threshold: 0.7
  database:
    path: /data/speciesid.db
  webui:
    port: 7767
    host: "0.0.0.0"
schema:
  frigate:
    frigate_url: "str"
    mqtt_server: "str"
    mqtt_auth: "bool"
    mqtt_username: "str?"
    mqtt_password: "str?"
    main_topic: "str"
    camera:
      - "str"
    object: "str"
  classification:
    model: "str"
    name_database: "str"
    threshold: "float"
  database:
    path: "str"
  webui:
    port: "int"
    host: "str"
